name: Complex CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: npm run inital
      - name: npm test
        run: npm run test

  build:
    runs-on: ubuntu-latest
    needs: [test]
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: npm run inital
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: build docker
        run: |
          docker build -t complex/multi-client ./client
          docker build -t complex/multi-nginx ./nginx
          docker build -t complex/multi-server ./server
          docker build -t complex/multi-worker ./worker
